# Generated by Django 3.1.3 on 2020-11-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
